spring:
  application:
    name: my-map

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/myMapDb
    username: root
    password: seowondev22!

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: fortestseowon@gmail.com
    password: hwtj mijq nhpg luae
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection timeout: 5000
          timeout: 5000
          write timeout: 5000

  data:
    redis:
      host: localhost
      port: 6379